# Generated by Django 5.0.1 on 2025-01-26 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='rol',
            field=models.CharField(choices=[('admin', 'Administrador'), ('estudiante', 'Estudiante')], default='estudiante', max_length=10),
        ),
    ]
