# Generated by Django 5.0.1 on 2025-01-26 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0003_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='rol',
            field=models.BooleanField(default=False),
        ),
    ]
